services:
  flask:
    build:
      context: .
    container_name: flask
    ports:
      - 9090:8080
    depends_on:
      - mysql
    volumes:
      - ./:/app
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    container_name: mysql
    ports:
      - "36000:3306"
    volumes:
      - ./db:/var/lib/mysql